<?php echo $this->doctype(); ?>

<html>
<head lang="en">
    <meta charset="UTF-8">
    <title><?php echo $this->escapeHtml($this->title) . ' - ' . $this->escapeHtml($this->appName); ?></title>
</head>
<body>
    <header>
        <h1><?php echo $this->escapeHtml($this->title); ?></h1>
    </header>

    <div id="content">
        <?php echo $this->content; ?>
    </div>

    <hr>
    <div id="footer">
        <footer>
            <p style="text-align: right;">curso zf2 - &copy; <?php echo date('Y') ?> by Ismael Trascastro
        </footer>
    </div>
</body>
</html>

