<div>
    <p>>><?php echo $this->escapeHtml($this->breadcrumb); ?></p>

    <ul class="list-inline">
        <li><a href="<?php echo $this->url('calculator'); ?>">Home</a></li>
        <li><a href="<?php echo $this->url('add'); ?>">Add</a></li>
        <li><a href="<?php echo $this->url('subtract'); ?>">Subtract</a></li>
        <li><a href="<?php echo $this->url('multiply'); ?>">Multiply</a></li>
        <li><a href="<?php echo $this->url('divide'); ?>">Divide</a></li>
    </ul>
</div>